### PR TITLE
+ Yorkshire

### PR DESCRIPTION
**Pull request by lucymhdavies**
Needs somebody to source an appropriate image, so obvs not ready to merge yet.

(and may want to wait until we've run more than 2 events/moved over to Meetup.com?)

### CODE REVIEW

**Comment by lucymhdavies** [comment]
I'm not a front-end dev, but (with the exception of the complete lack of image) it appears to work okay on all resolutions, at least in Chrome.

**Comment by lucymhdavies** [comment]
Added @wheresalice's image for now

**Comment by lucymhdavies** [comment]
Actually, wow, that's 5MB. Forgot to shrink it.

**Comment by dirv** [comment]
👍

**Pull request merged**
